- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0a28c2e9a030ff368
    ami_id: ami-0220d79f3f480ecf5
    sub_id: subnet-00cb815097e9622c0
    domain: sandeepinfo.online
    env: dev
    action: create
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      vpc_subnet_id: "{{ sub_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}"   
      tags: 
        project: "roboshop"
        component: "{{ item }}"
        Envrionment: "{{ env }}"
        name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"

  - name: print the ec2 ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
      when: action == "create"

  - name: Create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ item.item }}-{{ env }}.{{ domain }}" #mongodb.sandeepinfo.online
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"

  - name: Create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "roboshop-{{ env }}.{{ domain }}" #mongodb.sandeepinfo.online
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "frontend"
    - action == "create"

  - name: Delete route53 records
    amazon.aws.route53:
      state: abscent
      zone: "{{ domain }}"
      record: "roboshop-{{ env }}.{{ domain }}" #mongodb.sandeepinfo.online
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"


  - name: Teminate Ec2 instance
    amazon.aws.ec2_instance:
      state: abscent
      name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    when: action == "destroy"
    